package main

// DO NOT EDIT
// Generated by: ./tools/gen_sprite_tags.sh

type bossAnimationTags uint8

const (
	bossIdle1 bossAnimationTags = iota
	bossWalking1
	bossHit1
	bossIdle2
	bossWalking2
	bossHit2
	bossWalking3
	bossIdle3
	bossDeath1
	bossPhase2
	bossIdle4
	bossRunning
	bossDeath2
)
